language: python
python:
  - "3.10.12"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

# command to run tests
script:
  - python manage.py makemigrations --settings=emmerce_crm_backend.settings.test
  - python manage.py migrate --settings=emmerce_crm_backend.settings.test
  - coverage run --source=emmerce_crm_backend.apps ./manage.py test --settings=emmerce_crm_backend.settings.test

after_script:
  - coverage xml

after_success:
  - coverallslanguage: python
  - coveralls
