version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  celery_worker:
    build: .
    command: celery -A emmerce_crm_backend worker --loglevel=info
    depends_on:
      - redis
