name: Emmerce backend test with SQLite3

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.10.12]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Create .env file
        run: |
          echo "SECRET_KEY=This_secret_key!!!#@!" >> .env
          echo "DEBUG=True" >> .env
          echo "DB_ENGINE=django.db.backends.sqlite3" >> .env
          echo "DB_NAME=:memory:" >> .env
          echo "EMAIL_HOST_USER=email@example.com" >> .env
          echo "EMAIL_HOST_PASSWORD=emailpassword" >> .env
          echo "ALLOWED_HOSTS=*" >> .env

      - name: Set DJANGO_SETTINGS_MODULE
        run: |
          echo "DJANGO_SETTINGS_MODULE=emmerce_crm_backend.settings.test" >> $GITHUB_ENV

      - name: Create Static Files Directory
        run: mkdir -p static_files

      - name: Apply Migrations
        run: |
          python manage.py makemigrations authentication
          python manage.py migrate authentication
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests with Coverage
        run: |
          coverage run --source='emmerce_crm_backend' manage.py test

      - name: Generate Coverage Report
        run: |
          coverage report -m
          coverage xml

      - name: Upload Coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
